/* AUTO-GENERATED by hash_codegen.cmake — do not edit, do not commit.
 * Content hash of the recompiler codegen sources; folded into the overlay cache
 * path so an emitter change never reuses a stale DLL. */
#pragma once
#define PSX_OVERLAY_CODEGEN_HASH 0x6a49d04du
